rabbitmq:
  image: rabbitmq

redis:
  image: redis

sensu-api:
  image: sensu
  links:
    - redis
    - rabbitmq
  command: "/opt/sensu/bin/sensu-api -c /etc/sensu/config.json -v"

sensu-server:
  image: sensu
  links:
    - sensu-api
    - redis
    - rabbitmq
  command: "/opt/sensu/bin/sensu-server -c /etc/sensu/config.json -v"

uchiwa:
  image: sensu
  links:
    - sensu-api
    - sensu-server
  ports:
    - "3001:3000"
  command: "/opt/uchiwa/bin/uchiwa -c /etc/sensu/uchiwa.json -p /opt/uchiwa/src/public"
  
